MediaBundle\Entity\Musique:
    type: entity
    table: null
    repositoryClass: MediaBundle\Repository\MusiqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        artiste:
            type: string
            length: 255
        genre:
            type: string
            length: 255
        support:
            type: string
            length: 255
        image:
            type: string
            length: 255

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
