media_album:
    resource: "@MediaBundle/Resources/config/routing/album.yml"
    prefix:   /

media_homepage:
    path:     /
    defaults: { _controller: MediaBundle:Default:index }

media_commentaire:
    resource: "@MediaBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire
